name: ASP.NET Core CI using Docker

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build and test using Docker on Ubuntu
      run: |
        chmod +x build.sh
        ./build.sh
      shell: bash
      if: matrix.os == 'ubuntu-16.04'
    - name: Build and test using Docker on Windows
      run: ./build.ps1
      shell: powershell
      if: matrix.os == 'windows-latest'
